apk add libstdc++6 libstdc++
So that gevent works

Resolves:

ImportError: Error loading shared library libstdc++.so.6: No such file or directory (needed by /usr/local/lib/python3.14/site-packages/greenlet/_greenlet.cpython-314-x86_64-linux-musl.so)